spring:
  jpa:
    generate-ddl: true
  data:
    rest:
      basePath: /api
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
server:
  port: 8081

---
spring:
  profiles: cloud
server:
  port: 8080  
eureka:
  instance:
    # This is defined as part of Cloud Foundry, see cf envs <APP NAME>
    # Having this set means the service is accessed from outside the CloudFoundry environment. It should be accessed from the inside
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80	

    # Attempt to register the secure HTTPS port exposed via the GDS Cloud Foundry
    securePortEnabled: true
    securePort: 443

    # This registers with the server using IP address
    # Not advisable within CloudFoundry where inter-app communication is blocked by default	
    # preferIpAddress: true
  client:
    serviceUrl:
      # Defined as a Cloud Foundry app property;  see cf envs <APP NAME>
      defaultZone: ${EUREKA_URL}